/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Decision */
        post: operations["post_decision_cases__case_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Case */
        post: operations["check_case_cases__case_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_cases__case_id__runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountView */
        AccountView: {
            /** Account Id */
            account_id: number;
            /** Masked Number */
            masked_number: string;
            /** Sub Accounts */
            sub_accounts: components["schemas"]["SubAccountView"][];
        };
        /** @enum {string} */
        Action: "approve" | "edit" | "reject" | "reply_only";
        /** BelowZero */
        BelowZero: {
            /** Available */
            available: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** CandidateView */
        CandidateView: {
            /** Fee Txn Id */
            fee_txn_id: number;
            /** Label */
            label: string;
        };
        /** @enum {string} */
        CaseStatus: "not_checked" | "checking" | "ready_to_refund" | "recommend_no_refund" | "needs_supervisor" | "needs_your_call" | "not_about_fee" | "done";
        /** CaseView */
        CaseView: {
            /** Actions */
            actions: components["schemas"]["Action"][];
            /** Can Pick Fee */
            can_pick_fee: boolean;
            /** Can Run */
            can_run: boolean;
            /** Candidates */
            candidates: components["schemas"]["CandidateView"][];
            /** Checking Run Id */
            checking_run_id: string | null;
            clause: components["schemas"]["ClauseView"] | null;
            conversation: components["schemas"]["ConversationView"];
            decision: components["schemas"]["DecisionView"] | null;
            draft: components["schemas"]["DraftView"] | null;
            evidence: components["schemas"]["EvidenceView"];
            fee: components["schemas"]["FeeView"] | null;
            /** Id */
            id: number;
            /** Language */
            language: string | null;
            member: components["schemas"]["MemberView"];
            /** Notes */
            notes: components["schemas"]["ReasonView"][];
            /** Reasons */
            reasons: components["schemas"]["ReasonView"][];
            recommendation: components["schemas"]["RecommendationView"];
            run: components["schemas"]["RunView"] | null;
            status: components["schemas"]["CaseStatus"];
            /** Summary */
            summary: string | null;
            topic: components["schemas"]["Topic"] | null;
        };
        /** CheckView */
        CheckView: {
            /** Facts */
            facts: {
                [key: string]: string | number | boolean | string[];
            };
            /** Label */
            label: string;
            /** Passed */
            passed: boolean;
        };
        /** ClauseView */
        ClauseView: {
            /** Doc Title */
            doc_title: string;
            /** Section */
            section: string;
            /** Text */
            text: string;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /**
             * Author
             * @enum {string}
             */
            author: "member" | "staff";
            /** Author Name */
            author_name: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConversationView */
        ConversationView: {
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
            /** Status */
            status: string;
            /** Subject */
            subject: string;
        };
        /**
         * DecisionRequest
         * @description What Luis decided. The amount is never here: it is always the run's fee (D-api-3). Length
         *     and content rules are checked by the handler, in the spec's order.
         */
        DecisionRequest: {
            action: components["schemas"]["Action"];
            /** Reason */
            reason?: string | null;
            /** Reply Text */
            reply_text: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** DecisionResult */
        DecisionResult: {
            /** Amount */
            amount: string | null;
            case_status: components["schemas"]["CaseStatus"];
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Refunded */
            refunded: boolean;
        };
        /** DecisionView */
        DecisionView: {
            action: components["schemas"]["Action"];
            /** Amount */
            amount: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** By */
            by: string;
            /** Refunded */
            refunded: boolean;
            /** Reply */
            reply: string | null;
        };
        /** DraftView */
        DraftView: {
            /**
             * Source
             * @enum {string}
             */
            source: "model" | "template";
            /** Text */
            text: string;
        };
        /** EvidenceView */
        EvidenceView: {
            /** Checks */
            checks: components["schemas"]["CheckView"][];
            fee_day: components["schemas"]["FeeDayView"] | null;
            refunds_in_window: components["schemas"]["RefundsWindowView"] | null;
            standing: components["schemas"]["StandingView"] | null;
        };
        /** FeeDayRow */
        FeeDayRow: {
            /** Amount */
            amount: string;
            /** Balance After */
            balance_after: string;
            /** Description */
            description: string;
            /** Is Deposit */
            is_deposit: boolean;
            /** Is Fee */
            is_fee: boolean;
            /** Kind */
            kind: string;
            /** Position */
            position: number;
        };
        /** FeeDayView */
        FeeDayView: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rows */
            rows: components["schemas"]["FeeDayRow"][];
            /** Summary */
            summary: string | null;
        };
        /** FeeView */
        FeeView: {
            /** Amount */
            amount: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /** Fee Txn Id */
            fee_txn_id: number;
            /** Fee Type */
            fee_type: string | null;
            /** Source */
            source: ("rule" | "jev" | "staff") | null;
            /** Sub Account Name */
            sub_account_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            provider_mode: components["schemas"]["ProviderModes"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
            /** Version */
            version: string;
        };
        /** MemberView */
        MemberView: {
            /** Accounts */
            accounts: components["schemas"]["AccountView"][];
            /** Name */
            name: string;
        };
        /** ProviderModes */
        ProviderModes: {
            /**
             * Jev
             * @enum {string}
             */
            jev: "live" | "replay";
            /**
             * Openai
             * @enum {string}
             */
            openai: "live" | "replay";
        };
        /** QueueItem */
        QueueItem: {
            /** Amount */
            amount: string | null;
            /** Checked At */
            checked_at: string | null;
            /** Id */
            id: number;
            /** Member Name */
            member_name: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            status: components["schemas"]["CaseStatus"];
            /** Subject */
            subject: string;
            topic: components["schemas"]["Topic"] | null;
        };
        /** QueuePage */
        QueuePage: {
            /** Items */
            items: components["schemas"]["QueueItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ReasonView */
        ReasonView: {
            /** Message */
            message: string;
            /** Next Step */
            next_step: string | null;
        };
        /** RecommendationView */
        RecommendationView: {
            /**
             * Action
             * @enum {string}
             */
            action: "refund" | "no_refund" | "none";
            /** Amount */
            amount: string | null;
        };
        /** RefundRow */
        RefundRow: {
            /** Amount */
            amount: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Fee Type */
            fee_type: string | null;
        };
        /** RefundsWindowView */
        RefundsWindowView: {
            /** Count */
            count: number;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Items */
            items: components["schemas"]["RefundRow"][];
            /** Max Allowed */
            max_allowed: number;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** RunRequest */
        RunRequest: {
            /** Fee Txn Id */
            fee_txn_id?: number | null;
        };
        /** RunStarted */
        RunStarted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** RunView */
        RunView: {
            /** Checked At */
            checked_at: string | null;
            /** Cost Usd */
            cost_usd: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Provider Mode */
            provider_mode: {
                [key: string]: string;
            };
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Steps */
            steps: components["schemas"]["StepView"][];
        };
        /** StandingView */
        StandingView: {
            /** Below Zero */
            below_zero: components["schemas"]["BelowZero"][];
            /** Ok */
            ok: boolean;
        };
        /** StepView */
        StepView: {
            /** Latency Ms */
            latency_ms: number;
            /** Node */
            node: string;
            /**
             * State
             * @enum {string}
             */
            state: "finished" | "failed";
        };
        /** SubAccountView */
        SubAccountView: {
            /** Available */
            available: string;
            /** Balance */
            balance: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** @enum {string} */
        Topic: "fee_refund_request" | "fee_question" | "card_issue" | "account_update" | "statement_question" | "other";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases_cases_get: {
        parameters: {
            query?: {
                view?: "open" | "done";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_decision_cases__case_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_case_cases__case_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_cases__case_id__runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
