"""Initial schema: the brief's five tables, the extensions, policy clauses and the app tables.

Generated from backend/db/models.py with Alembic autogenerate, then adjusted by hand:
- cases.latest_run_id -> agent_runs is circular, so that foreign key is added after both tables.
- audit_events gets a trigger that rejects UPDATE and DELETE (append-only, SPEC-data).

Revision ID: 0001
Revises:
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("credit_union_id", sa.BigInteger(), nullable=False),
        sa.Column("account_number", sa.Text(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(op.f("ix_accounts_member_id"), "accounts", ["member_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_case_id"), "audit_events", ["case_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('waiting_for_bank', 'waiting_for_member', 'read_by_bank', 'closed')",
            name=op.f("ck_conversations_status_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_status_created_at"),
        "conversations",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "member_profiles",
        sa.Column("member_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("member_id", name=op.f("pk_member_profiles")),
    )
    op.create_table(
        "policy_clauses",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("doc_slug", sa.Text(), nullable=False),
        sa.Column("doc_title", sa.Text(), nullable=False),
        sa.Column("section", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column(
            "search",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', doc_title || ' ' || section), 'A') || "
                "setweight(to_tsvector('english', text), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_clauses")),
    )
    op.create_index(
        op.f("ix_policy_clauses_search"),
        "policy_clauses",
        ["search"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "staff",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
    )
    op.create_table(
        "cases",
        sa.Column("conversation_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("latest_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('not_checked', 'checking', 'ready_to_refund', 'recommend_no_refund', "
            "'needs_supervisor', 'needs_your_call', 'not_about_fee', 'done')",
            name=op.f("ck_cases_status_allowed"),
        ),
        sa.CheckConstraint(
            "topic IN ('fee_refund_request', 'fee_question', 'card_issue', 'account_update', "
            "'statement_question', 'other')",
            name=op.f("ck_cases_topic_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_cases_conversation_id_conversations"),
        ),
        sa.PrimaryKeyConstraint("conversation_id", name=op.f("pk_cases")),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1000000), nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        op.f("ix_messages_conversation_id_created_at"),
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sub_accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("available", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint(
            "type IN ('SAVINGS', 'CHECKING', 'LOAN')", name=op.f("ck_sub_accounts_type_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_sub_accounts_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sub_accounts")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column(
            "reason_codes",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("would_auto_approve", sa.Boolean(), nullable=True),
        sa.Column("classifier_used", sa.Text(), nullable=True),
        sa.Column("provider_mode", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("policy_version", sa.Text(), nullable=True),
        sa.Column("prompt_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_latency_ms", sa.Integer(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("tokens_cached", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.CheckConstraint(
            "classifier_used IN ('jev', 'backup')",
            name=op.f("ck_agent_runs_classifier_used_allowed"),
        ),
        sa.CheckConstraint(
            "outcome IN ('ready_to_refund', 'recommend_no_refund', 'needs_supervisor', "
            "'needs_your_call', 'not_about_fee')",
            name=op.f("ck_agent_runs_outcome_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'interrupted')",
            name=op.f("ck_agent_runs_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.conversation_id"], name=op.f("fk_agent_runs_case_id_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        op.f("ix_agent_runs_case_id_started_at"),
        "agent_runs",
        ["case_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "uq_agent_runs_one_running_per_case",
        "agent_runs",
        ["case_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_foreign_key(
        op.f("fk_cases_latest_run_id_agent_runs"), "cases", "agent_runs", ["latest_run_id"], ["id"]
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1000000), nullable=False),
        sa.Column("sub_account_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("posting_ref", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "posting_ref ~ '^\\d{8}-\\d{4}$'", name=op.f("ck_transactions_posting_ref_format")
        ),
        sa.ForeignKeyConstraint(
            ["sub_account_id"],
            ["sub_accounts.id"],
            name=op.f("fk_transactions_sub_account_id_sub_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint(
            "sub_account_id", "posting_ref", name=op.f("uq_transactions_sub_account_id_posting_ref")
        ),
    )
    op.create_index(
        op.f("ix_transactions_sub_account_id_date"),
        "transactions",
        ["sub_account_id", "date"],
        unique=False,
    )
    op.create_table(
        "agent_steps",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("node", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("tokens_cached", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("input_masked", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "kind IN ('rule', 'jev', 'llm', 'tool')", name=op.f("ck_agent_steps_kind_allowed")
        ),
        sa.CheckConstraint(
            "status IN ('finished', 'failed')", name=op.f("ck_agent_steps_status_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_agent_steps_run_id_agent_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_steps")),
    )
    op.create_index(op.f("ix_agent_steps_run_id"), "agent_steps", ["run_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("staff_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("final_reply", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('approve', 'edit', 'reject', 'reply_only')",
            name=op.f("ck_decisions_action_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.conversation_id"], name=op.f("fk_decisions_case_id_cases")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_decisions_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_decisions_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_decisions_idempotency_key")),
    )
    op.create_index(op.f("ix_decisions_case_id"), "decisions", ["case_id"], unique=False)
    op.create_table(
        "eval_candidates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("masked_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('edit', 'reject', 'reply_only')", name=op.f("ck_eval_candidates_kind_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.conversation_id"], name=op.f("fk_eval_candidates_case_id_cases")
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_eval_candidates_decision_id_decisions")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_eval_candidates_run_id_agent_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_candidates")),
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("fee_txn_id", sa.BigInteger(), nullable=False),
        sa.Column("refund_txn_id", sa.BigInteger(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_refunds_amount_positive")),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_refunds_decision_id_decisions")
        ),
        sa.ForeignKeyConstraint(
            ["fee_txn_id"], ["transactions.id"], name=op.f("fk_refunds_fee_txn_id_transactions")
        ),
        sa.ForeignKeyConstraint(
            ["refund_txn_id"],
            ["transactions.id"],
            name=op.f("fk_refunds_refund_txn_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
        sa.UniqueConstraint("fee_txn_id", name=op.f("uq_refunds_fee_txn_id")),
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE FUNCTION reject_audit_change() RETURNS trigger LANGUAGE plpgsql AS $$ "
        "BEGIN RAISE EXCEPTION 'audit_events is append-only'; END $$"
    )
    op.execute(
        "CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events "
        "FOR EACH ROW EXECUTE FUNCTION reject_audit_change()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION reject_audit_change()")
    op.drop_constraint(op.f("fk_cases_latest_run_id_agent_runs"), "cases", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refunds")
    op.drop_table("eval_candidates")
    op.drop_index(op.f("ix_decisions_case_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_agent_steps_run_id"), table_name="agent_steps")
    op.drop_table("agent_steps")
    op.drop_index(op.f("ix_transactions_sub_account_id_date"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(
        "uq_agent_runs_one_running_per_case",
        table_name="agent_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(op.f("ix_agent_runs_case_id_started_at"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("sub_accounts")
    op.drop_index(op.f("ix_messages_conversation_id_created_at"), table_name="messages")
    op.drop_table("messages")
    op.drop_table("cases")
    op.drop_table("staff")
    op.drop_index(
        op.f("ix_policy_clauses_search"), table_name="policy_clauses", postgresql_using="gin"
    )
    op.drop_table("policy_clauses")
    op.drop_table("member_profiles")
    op.drop_index(op.f("ix_conversations_status_created_at"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_audit_events_case_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_accounts_member_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
